name: auto clock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  my-job1:
    runs-on: ubuntu-20.04
    steps:
      - name: check
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install selenium
          pip install ddddocr
          pip install lxml
          pip install requests
          pip install opencv-python
          pip install opencv-contrib-python
      - name: Install chromedriver
        run: |
          wget https://www.slimjet.com/chrome/download-chrome.php?file=files%2F104.0.5112.102%2Fgoogle-chrome-stable_current_amd64.deb -O google-chrome-stable_current_amd64.deb
          wget https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip
          sudo apt install ./google-chrome-stable_current_amd64.deb --allow-downgrades
          unzip chromedriver_linux64.zip
          sudo mv ./chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Work
        run: |
          google-chrome --no-sandbox --headless --remote-debugging-port=12306 & python3 ./main.py
      
        
        
