name: auto clock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          pip install selenium
          pip install ddddocr
          pip install lxml
          pip install requests
          pip install opencv-python
          pip install opencv-contrib-python
          pip install undetected_chromedriver
      - name: Install chromedriver
        uses: logikal-io/install-chrome@v1
      - name: Work
        run: |
          python ./main.py
      
        
        
