name: auto clock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  my-job1:
    runs-on: ubuntu-20.04
    steps:
      - name: check
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install selenium
          pip install ddddocr
          pip install lxml
          pip install requests
          pip install opencv-python
          pip install opencv-contrib-python
          pip install undetected_chromedriver==3.4.5
      - name: Install chromedriver
        run: |
          wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1084013%2Fchrome-linux.zip?generation=1671143102457414&alt=media
          wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1084013%2Fchromedriver_linux64.zip?generation=1671143107889609&alt=media
          unzip Linux_x64_1084013_chrome-linux.zip
          unzip chromedriver_linux64.zip
          sudo mv ./chromedriver_linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Work
        run: |
          python3 ./main.py
      
        
        
